-- CHECK ABNORMAL DATA
select
  (q40 IS NULL) +
  (q50 IS NULL) +
  (q60 IS NULL) +
  (q70 IS NULL) +
  (q80 IS NULL) +
  (q90 IS NULL) +
  (q100 IS NULL) AS missing_count,
  COUNT(*) AS n
FROM gad7_responses
GROUP BY missing_count
ORDER BY missing_count;

SELECT
  SUM(q40 NOT BETWEEN 0 AND 3) AS bad_q40,
  SUM(q50 NOT BETWEEN 0 AND 3) AS bad_q50,
  SUM(q60 NOT BETWEEN 0 AND 3) AS bad_q60,
  SUM(q70 NOT BETWEEN 0 AND 3) AS bad_q70,
  SUM(q80 NOT BETWEEN 0 AND 3) AS bad_q80,
  SUM(q90 NOT BETWEEN 0 AND 3) AS bad_q90,
  SUM(q100 NOT BETWEEN 0 AND 3) AS bad_q100
FROM gad7_responses;

-- CHANGE TIMESTEP TO AGE
UPDATE gad7_responses
SET age = FROM_UNIXTIME(CAST(age AS UNSIGNED) / 1000);

UPDATE gad7_responses
SET age = TIMESTAMPDIFF(
    YEAR,
    age,
    DATE('2018-07-05')
);

SELECT
    COUNT(*) AS n,
    MIN(age) AS min_age,
    MAX(age) AS max_age,
    ROUND(AVG(age),2) AS mean_age,
    ROUND(STDDEV(age),2) AS std_age
FROM gad7_responses
WHERE age IS NOT NULL;

ALTER TABLE gad7_responses 
ADD COLUMN age_group VARCHAR(20);

-- BUILD AGE GROUPS
UPDATE gad7_responses
SET age_group = CASE
    WHEN age < 25 THEN 'Under 25'
    WHEN age BETWEEN 25 AND 34 THEN '25-34'
    WHEN age BETWEEN 35 AND 44 THEN '35-44'
    ELSE '45+'
END;

ALTER TABLE gad7_responses DROP COLUMN age_group;

ALTER TABLE gad7_responses 
ADD COLUMN age_group VARCHAR(20);

UPDATE gad7_responses
SET age_group = CASE
    WHEN age < 25 THEN 'Under 25'
    WHEN age BETWEEN 25 AND 34 THEN '25-34'
    WHEN age BETWEEN 35 AND 44 THEN '35-44'
    WHEN age BETWEEN 45 AND 54 THEN '45-54'
    WHEN age BETWEEN 55 AND 64 THEN '55-64'
    ELSE '65+'
END;

SELECT age_group, COUNT(*) AS n
FROM gad7_responses
GROUP BY age_group
ORDER BY age_group;

-- CHECK OCCUPATION MISSING VALUE
select occupation, count('occupation')
from gad7_responses
group by occupation;

UPDATE gad7_responses
SET occupation = 'Unknown'
WHERE occupation IS NULL;

-- SPLIT MULTIPLE CHOICE VARIABLES INTO SINGLE VARIABLE
ALTER TABLE gad7_responses
  ADD COLUMN q500_0 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q500_1 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q500_2 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q500_3 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q500_4 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q500_5 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q500_6 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q500_7 TINYINT NOT NULL DEFAULT 0;
  
UPDATE gad7_responses
SET
  q500_0 = CASE WHEN REGEXP_LIKE(`q500`, '(^|\\|)0(\\||$)') THEN 1 ELSE 0 END,
  q500_1 = CASE WHEN REGEXP_LIKE(`q500`, '(^|\\|)1(\\||$)') THEN 1 ELSE 0 END,
  q500_2 = CASE WHEN REGEXP_LIKE(`q500`, '(^|\\|)2(\\||$)') THEN 1 ELSE 0 END,
  q500_3 = CASE WHEN REGEXP_LIKE(`q500`, '(^|\\|)3(\\||$)') THEN 1 ELSE 0 END,
  q500_4 = CASE WHEN REGEXP_LIKE(`q500`, '(^|\\|)4(\\||$)') THEN 1 ELSE 0 END,
  q500_5 = CASE WHEN REGEXP_LIKE(`q500`, '(^|\\|)5(\\||$)') THEN 1 ELSE 0 END,
  q500_6 = CASE WHEN REGEXP_LIKE(`q500`, '(^|\\|)6(\\||$)') THEN 1 ELSE 0 END,
  q500_7 = CASE WHEN REGEXP_LIKE(`q500`, '(^|\\|)7(\\||$)') THEN 1 ELSE 0 END;
  
ALTER TABLE gad7_responses
  ADD COLUMN q510_0 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q510_1 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q510_2 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q510_3 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q510_4 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q510_5 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q510_6 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q510_7 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q510_8 TINYINT NOT NULL DEFAULT 0;
  
UPDATE gad7_responses
SET
  q510_0 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)0(\\||$)') THEN 1 ELSE 0 END,
  q510_1 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)1(\\||$)') THEN 1 ELSE 0 END,
  q510_2 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)2(\\||$)') THEN 1 ELSE 0 END,
  q510_3 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)3(\\||$)') THEN 1 ELSE 0 END,
  q510_4 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)4(\\||$)') THEN 1 ELSE 0 END,
  q510_5 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)5(\\||$)') THEN 1 ELSE 0 END,
  q510_6 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)6(\\||$)') THEN 1 ELSE 0 END,
  q510_7 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)7(\\||$)') THEN 1 ELSE 0 END,
  q510_8 = CASE WHEN REGEXP_LIKE(REPLACE(`q510`, ' ', ''), '(^|\\|)8(\\||$)') THEN 1 ELSE 0 END;
  
ALTER TABLE gad7_responses
  ADD COLUMN q520_0 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_1 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_2 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_3 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_4 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_5 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_6 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_7 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_8 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q520_9 TINYINT NOT NULL DEFAULT 0;
  
UPDATE gad7_responses
SET
  q520_0 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)0(\\||$)') THEN 1 ELSE 0 END,
  q520_1 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)1(\\||$)') THEN 1 ELSE 0 END,
  q520_2 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)2(\\||$)') THEN 1 ELSE 0 END,
  q520_3 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)3(\\||$)') THEN 1 ELSE 0 END,
  q520_4 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)4(\\||$)') THEN 1 ELSE 0 END,
  q520_5 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)5(\\||$)') THEN 1 ELSE 0 END,
  q520_6 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)6(\\||$)') THEN 1 ELSE 0 END,
  q520_7 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)7(\\||$)') THEN 1 ELSE 0 END,
  q520_8 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)8(\\||$)') THEN 1 ELSE 0 END,
  q520_9 = CASE WHEN REGEXP_LIKE(REPLACE(`q520`, ' ', ''), '(^|\\|)9(\\||$)') THEN 1 ELSE 0 END;
  
ALTER TABLE gad7_responses
  ADD COLUMN q530_0 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q530_1 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q530_2 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q530_3 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q530_4 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q530_5 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q530_6 TINYINT NOT NULL DEFAULT 0;
  
UPDATE gad7_responses
SET
  q530_0 = CASE WHEN REGEXP_LIKE(REPLACE(`q530`, ' ', ''), '(^|\\|)0(\\||$)') THEN 1 ELSE 0 END,
  q530_1 = CASE WHEN REGEXP_LIKE(REPLACE(`q530`, ' ', ''), '(^|\\|)1(\\||$)') THEN 1 ELSE 0 END,
  q530_2 = CASE WHEN REGEXP_LIKE(REPLACE(`q530`, ' ', ''), '(^|\\|)2(\\||$)') THEN 1 ELSE 0 END,
  q530_3 = CASE WHEN REGEXP_LIKE(REPLACE(`q530`, ' ', ''), '(^|\\|)3(\\||$)') THEN 1 ELSE 0 END,
  q530_4 = CASE WHEN REGEXP_LIKE(REPLACE(`q530`, ' ', ''), '(^|\\|)4(\\||$)') THEN 1 ELSE 0 END,
  q530_5 = CASE WHEN REGEXP_LIKE(REPLACE(`q530`, ' ', ''), '(^|\\|)5(\\||$)') THEN 1 ELSE 0 END,
  q530_6 = CASE WHEN REGEXP_LIKE(REPLACE(`q530`, ' ', ''), '(^|\\|)6(\\||$)') THEN 1 ELSE 0 END;
  
ALTER TABLE gad7_responses
  ADD COLUMN q540_0 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q540_1 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q540_2 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q540_3 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q540_4 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q540_5 TINYINT NOT NULL DEFAULT 0;
  
UPDATE gad7_responses
SET
  q540_0 = CASE WHEN REGEXP_LIKE(REPLACE(`q540`, ' ', ''), '(^|\\|)0(\\||$)') THEN 1 ELSE 0 END,
  q540_1 = CASE WHEN REGEXP_LIKE(REPLACE(`q540`, ' ', ''), '(^|\\|)1(\\||$)') THEN 1 ELSE 0 END,
  q540_2 = CASE WHEN REGEXP_LIKE(REPLACE(`q540`, ' ', ''), '(^|\\|)2(\\||$)') THEN 1 ELSE 0 END,
  q540_3 = CASE WHEN REGEXP_LIKE(REPLACE(`q540`, ' ', ''), '(^|\\|)3(\\||$)') THEN 1 ELSE 0 END,
  q540_4 = CASE WHEN REGEXP_LIKE(REPLACE(`q540`, ' ', ''), '(^|\\|)4(\\||$)') THEN 1 ELSE 0 END,
  q540_5 = CASE WHEN REGEXP_LIKE(REPLACE(`q540`, ' ', ''), '(^|\\|)5(\\||$)') THEN 1 ELSE 0 END;

ALTER TABLE gad7_responses
  ADD COLUMN q560_0 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q560_1 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q560_2 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q560_3 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q560_4 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q560_5 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q560_6 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q560_7 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q560_8 TINYINT NOT NULL DEFAULT 0;

UPDATE gad7_responses
SET
  q560_0 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)0(\\||$)') THEN 1 ELSE 0 END,
  q560_1 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)1(\\||$)') THEN 1 ELSE 0 END,
  q560_2 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)2(\\||$)') THEN 1 ELSE 0 END,
  q560_3 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)3(\\||$)') THEN 1 ELSE 0 END,
  q560_4 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)4(\\||$)') THEN 1 ELSE 0 END,
  q560_5 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)5(\\||$)') THEN 1 ELSE 0 END,
  q560_6 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)6(\\||$)') THEN 1 ELSE 0 END,
  q560_7 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)7(\\||$)') THEN 1 ELSE 0 END,
  q560_8 = CASE WHEN REGEXP_LIKE(REPLACE(`q560`, ' ', ''), '(^|\\|)8(\\||$)') THEN 1 ELSE 0 END;
  
ALTER TABLE gad7_responses
  ADD COLUMN q580_0 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_1 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_2 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_3 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_4 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_5 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_6 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_7 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_8 TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN q580_9 TINYINT NOT NULL DEFAULT 0;
  
UPDATE gad7_responses
SET
  q580_0 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)0(\\||$)') THEN 1 ELSE 0 END,
  q580_1 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)1(\\||$)') THEN 1 ELSE 0 END,
  q580_2 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)2(\\||$)') THEN 1 ELSE 0 END,
  q580_3 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)3(\\||$)') THEN 1 ELSE 0 END,
  q580_4 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)4(\\||$)') THEN 1 ELSE 0 END,
  q580_5 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)5(\\||$)') THEN 1 ELSE 0 END,
  q580_6 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)6(\\||$)') THEN 1 ELSE 0 END,
  q580_7 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)7(\\||$)') THEN 1 ELSE 0 END,
  q580_8 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)8(\\||$)') THEN 1 ELSE 0 END,
  q580_9 = CASE WHEN REGEXP_LIKE(REPLACE(`q580`, ' ', ''), '(^|\\|)9(\\||$)') THEN 1 ELSE 0 END;